### ISSUE TITLE
;-;

### ISSUE THREAD

**Issue by folliejester** [system32uwu/animu-desu#2]
![image](https://user-images.githubusercontent.com/64592521/124772953-1f4b2080-df5a-11eb-9729-d47063160515.png)

**Comment by wiredmatt** [comment]
Hi, please update to the [latest version published in npm](https://www.npmjs.com/package/animu-desu/v/1.0.15).

```ts
import { setBaseURL, getPopular } from "./src";

setBaseURL("https://gogoanime.pe/");

getPopular(1)
  .then((res) => console.log(res))
  .catch((err) => console.log(err));
```

Also try to be somewhat descriptive when you open an issue, it will help me a lot. You could've also made a PR fixing this [since it's nothing complicated](https://github.com/system32uwu/animu-desu/commit/01a8e3026a46080144fff7f7686fed6531c93651). Basically gogoanime/.so was taken down, so you only had to change the domain in order for animu-desu to work as it was.

**Comment by wiredmatt** [comment]
I'm assuming this is solved now.
